stages:
  - build
  - deploy

before_script:
  - echo [INFO] 배포를 시작합니다...

frontend-build:
  stage: build
  image: node:22.13-alpine
  tags:
    - king-develop
  cache:
    paths:
      - king/node_modules
  script:
    - echo [INFO] 프론트엔드 파일 빌드중
    - cd king
    - echo VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY >> .env
    - echo VITE_GOOGLE_MAPS_MAP_ID=$VITE_GOOGLE_MAPS_MAP_ID >> .env
    - echo VITE_API_BASE_URL=$VITE_API_BASE_URL >> .env
    - echo VITE_MASTER_ACCESS_TOKEN=$VITE_MASTER_ACCESS_TOKEN >> .env
    - npm install
    - npm run build

  artifacts:
    paths:
      - king/dist

# 배포 단계
deploy:
  stage: deploy
  image: docker:latest
  tags:
    - king-develop
  script:
    - docker info
    - docker build -t testDocker king-backend/Dockerfile
    - docker run testDocker
