stages:
  - build
  - deploy

# 빌드 단계
build:
  stage: build
  script:
    - echo "빌드를 시작합니다."
    - echo "애플리케이션 빌드 중..."
    - sleep 5  # 빌드 과정을 시뮬레이션하기 위한 대기
    - echo "빌드 완료!"

# 배포 단계
deploy:
  stage: deploy
  script:
    - echo "배포 시작"
    - echo "배포 환경 준비 중..."
    - sleep 2  # 배포 과정을 시뮬레이션하기 위한 대기
    - echo "배포 완료!"
