stages:
  - build
  - deploy

before_script:
  - echo [INFO] 배포를 시작합니다...

frontend_build:
  stage: build
  only:
    changes:
        - king/**
  cache:
    paths:
      - king/node_modules
  tags:
    - king-develop
  script:
    - echo [INFO] 프론트엔드 파일 빌드중
    - cd king
    - echo VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY >> .env
    - echo VITE_GOOGLE_MAPS_MAP_ID=$VITE_GOOGLE_MAPS_MAP_ID >> .env
    - echo VITE_API_BASE_URL=$VITE_API_BASE_URL >> .env
    - echo VITE_MASTER_ACCESS_TOKEN=$VITE_MASTER_ACCESS_TOKEN >> .env
    - npm install
    - npm run build
