stages:
  - build
  - deploy

frontend-build:
  stage: build
  image: node:22.13-alpine
  tags:
    - king-prod
  before_script:
    - apk add --no-cache openssh-client rsync
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_KEY"
    - ssh-add "$SSH_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
  cache:
    paths:
      - king/node_modules
  script:
    - echo [INFO] 프론트엔드 파일 빌드 중
    - cd king
    - cat $CLIENT_ENV >> .env
    - npm install
    - npm run build
    - echo [INFO] 프론트엔드 파일 복사 중
    - rsync -avz --delete -e "ssh -i $SSH_KEY" dist/ $EC2_USER@$EC2_HOST:/home/ubuntu/app/king/dist/
