stages:
  - build
  - deploy

before_script:
  - echo [INFO] 배포를 시작합니다...

# 빌드 단계
build:
  stage: build
  image: node:22.13-alpine
  tags:
    - king-develop
  script:
    - echo [INFO] 프론트엔드 파일 빌드중
    - sleep 120
    - cd king
    - echo VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY >> .env
    - echo VITE_GOOGLE_MAPS_MAP_ID=$VITE_GOOGLE_MAPS_MAP_ID >> .env
    - echo VITE_API_BASE_URL=$VITE_API_BASE_URL >> .env
    - echo VITE_MASTER_ACCESS_TOKEN=$VITE_MASTER_ACCESS_TOKEN >> .env
    - npm install
    - npm run build


# 배포 단계
deploy:
  stage: deploy
  tags:
    - king-develop
  script:
    - echo "배포 시작"
    - echo "배포 환경 준비 중..."
    - sleep 2  # 배포 과정을 시뮬레이션하기 위한 대기
    - echo "배포 완료!"
